import { createSlice } from "@reduxjs/toolkit";
import anecdoteService from "../services/anecdotes";

const anecdoteSlice = createSlice({
	name: "anecdotes",
	initialState: [],
	reducers: {
		setAnecdotes(state, action) {
			return action.payload;
		},
		// here we finally update state (a big array of objects)
		appendAnecdote(state, action) {
			state.push(action.payload);
		},
		updateAnecdote(state, action) {
			console.log(action.payload);
			const id = action.payload.id;
			const anecdoteToVote = state.find((a) => a.id === id);
			const updatedAnecdote = {
				...anecdoteToVote,
				votes: anecdoteToVote.votes + 1,
			};
			return state.map((a) => (a.id !== id ? a : updatedAnecdote));
		},
	},
});

// these are the actions creators automatically generated by createSlice
export const { setAnecdotes, appendAnecdote, updateAnecdote } =
	anecdoteSlice.actions;

export const fetchAnecdotes = () => {
	return async (dispatch) => {
		const anecdotes = await anecdoteService.getAll();
		dispatch(setAnecdotes(anecdotes));
	};
};

// gets called from f.e., content is the string from the form
export const createAnecdote = (content) => {
	// the action creator returns an async function that waits for the server data
	return async (dispatch) => {
		const newAnecdote = await anecdoteService.createNew(content);
		// before dispatching the action creator that will make the store run its associated reducer and update state
		dispatch(appendAnecdote(newAnecdote));
	};
};

export const voteAnecdote = (content) => {
	const id = content.id;
	const votedAnecdote = {
		...content,
		votes: content.votes + 1,
	};
	return async (dispatch) => {
		const updatedAnecdote = await anecdoteService.update(id, votedAnecdote);
		// Qua aggiorno solo lo stato
		dispatch(updateAnecdote(updatedAnecdote));
	};
};
export default anecdoteSlice.reducer;
